name: 'Build'
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      kmonad_os: '[MAC]'
      miryoku_alphas: '["QWERTY"]'
      miryoku_extras: '["QWERTY"]'
      miryoku_tap: '["QWERTY"]'
      mode: '["build"]'
